const Admin_Action_Types = {
  ADMIN_SIGNIN_START: "ADMIN_SIGNIN_START",
  ADMIN_SIGNIN_SUCESS: "ADMIN_SIGNIN_SUCESS",
  ADMIN_SIGNIN_FAILURE: "ADMIN_SIGNIN_FAILURE",
  ADMIN_SIGN_UP_START: "ADMIN_SIGN_UP_START",
  ADMIN_SIGN_UP_SUCESS: "ADMIN_SIGN_UP_SUCESS",
  ADMIN_SIGN_UP_FAILURE: "ADMIN_SIGN_UP_FAILURE",
};

export default Admin_Action_Types;
